### ISSUE TITLE
When will it arrive on Melpa?

### ISSUE THREAD

**Issue by Compro-Prasad** [prassee/prassee-emacs-theme#2]

**Comment by prassee** [comment]
the plugin is submitted and waiting for the PR to merge https://github.com/melpa/melpa/pull/4572

**Comment by prassee** [comment]
@Compro-Prasad  its arrived on melpa !!! find it from here 
https://melpa.org/#/prassee-theme

**Comment by Compro-Prasad** [comment]
I have installed it.

**Comment by prassee** [comment]
👍
